config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  

  resources :conversations do
    resources :messages
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}

  post 'friendships/create' => 'friendships#create'
  delete 'friendships/:id' => 'friendships#destroy', as: :friendship

  get "users" => "users#index", as: :users
  get "users/:id" => "users#show", as: :user
  

 

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, class_name: 'Friendship', :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :conversations, :foreign_key => :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  #for image uploading via paperclip
  has_attached_file :image, :styles => { small: "64x64", med: "100x100", large: "200x200" }, :default_url=>"robot.png"
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.firstname = auth.info.first_name
    user.lastname = auth.info.last_name
    user.image = auth.info.image
    
    end
  end

  # def self.new_with_session(params, session)
  #   super.tap do |user|
  #     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #       user.email = data["email"] if user.email.blank?
  #     end
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end 

	# def show
	# 	@user = User.find(params[:id])
	# end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% @users.each do |u| %>
	<tr class = "usershow">
		<td class = "usershow">Firstname:<strong><%= u.firstname %></strong></td><br>
		<td class = "usershow">Lastname:<strong><%= u.lastname %></strong></td><br>
		<td class = "usershow"><%= image_tag u.image(:large)%></td><br>
		<td class = "usershow"><%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
	                    "data-sid" => current_user.id, "data-rip" => u.id %>

      		</td><br>
      		<td class = "usershow"><%= link_to "Add Friend", friendships_create_path(:friend_id => u), :method => :post %></td><br>
      	</tr>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

Hello <%= current_user.firstname%><br>
<%#= current_user.email %><!-- <br> -->
<%#= current_user.firstname %><!-- <br> -->
<%#= current_user.lastname %><!-- <br> -->
<%= image_tag current_user.image(:small)%><!-- <br> -->

<h2>Your Friends</h2>
<h3>You have <%= current_user.friendships.count %></h3>
<ul><% for friendship in current_user.friendships %>
		<td><%= friendship.friend.firstname %></td>
		<td><%= link_to "remove", friendship, :method => :delete %></td><br>

		
	<% end %></ul>
<h2>Friended by Users</h2>
	<ul>
		<% for user in current_user.inverse_friends %>
			<td><%= user.name %></td>
		<% end %>
	</ul>


	





<p><%= link_to "Find Friends", users_path %></p>

<%= link_to "edit my profile", edit_user_registration_path(current_user) %>